package pl.playmobile.channel.utils;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.17
 * 2015-09-25T13:57:04.136+02:00
 * Generated source version: 2.7.17
 * 
 */
@WebService(targetNamespace = "http://playmobile.pl/channel/utils", name = "queueMessagePortType")
@XmlSeeAlso({org.p4.esb.ObjectFactory.class, pl.project4.utils.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface QueueMessagePortType {

    @WebMethod(action = "http://project4.pl/utils/queueMessages")
    public void queueMessages(
        @WebParam(partName = "queueMessages", name = "queueMessages", targetNamespace = "http://project4.pl/utils")
        pl.project4.utils.QueueMessages queueMessages
    ) throws ServiceFault;

    @WebMethod(action = "http://project4.pl/utils/queueMessage")
    public void queueMessage(
        @WebParam(partName = "queueMessage", name = "queueMessage", targetNamespace = "http://project4.pl/utils")
        pl.project4.utils.QueueMessage queueMessage
    ) throws ServiceFault;

    @WebMethod(action = "http://project4.pl/utils/cancelMessage")
    public void cancelMessage(
        @WebParam(partName = "cancelMessage", name = "cancelMessage", targetNamespace = "http://project4.pl/utils")
        pl.project4.utils.CancelMessage cancelMessage
    ) throws ServiceFault;
}
